### PR TITLE
Update with mingw32 support

### PR DESCRIPTION
**Pull request by JL2210**
Updates to add mingw32 support, removes lines that break build from configure.ac, and adds an `#ifdef` statement to shc.c to block _SC_ARG_MAX from causing compilation errors.

### CODE REVIEW

**Comment by JL2210** [comment]
@neurobin, sorry to bother you, but is there anything wrong with this? I submitted it over a week ago, and I haven't received any feedback on it.

**Comment by neurobin** [comment]
Can you please explain why it is necessary to block _SC_ARG_MAX for mingw32 ...

**Comment by JL2210** [comment]
Sure. _SC_ARG_MAX is a POSIX variable. Windows is not POSIX compliant.

**Comment by JL2210** [comment]
I could define the variable if WIN32 or WIN64 is defined. If I remember correctly, the proper value is 32768.

**Comment by JL2210** [comment]
I couldn't find a workaround for that. I'd say this works fairly well. Is it OK now?

**Comment by JL2210** [comment]
I'm closing this. It doesn't work very well, considering Bash isn't installed in Windows, and the variables that it needs aren't defined. Sorry for wasting your time.

**Pull request closed without merging**
