### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mathieu-aubin**

### CODE REVIEW

**Comment by JL2210** [comment]
You know, this isn't going to be able to build without a `NEWS` file.

**Comment by mathieu-aubin** [comment]
> 
> 
> You know, this isn't going to be able to build without a `NEWS` file.

Building doesn't seem to be a problem

[asciicast](https://asciinema.org/a/wmzkaje7flQuJJylzoSnMXnQ9)

**Comment by JL2210** [comment]
Yes, but please note that that's why the Travis CI build is failing.

**Comment by neurobin** [comment]
Seems the man changed a lot. Did you manually edit it or create it from man.md with pandoc `pandoc -s man.md -t man -o shc.1`?

**Pull request merged**
