### PR TITLE
Add extra security flag 'Z' (untraceable, undumpable and root is not needed)

### PR DESCRIPTION
**Pull request by intika**
After https://github.com/existz/shc-3.8.9/issues/5 
And https://github.com/neurobin/shc/issues/29
And https://github.com/neurobin/shc/issues/53
And maybe https://github.com/neurobin/shc/issues/23

Here is my little grain of salt, have a look, its not a lot but it could be useful ;)

### CODE REVIEW

**Comment by neurobin** [comment]
nice one!! way to go. But I would like this to be the default behavior, i.e the z flag would be turned on by default. Actually there shouldn't be any z flag at all, to turn traceable on we can bring back the old option `-T`.

**Comment by neurobin** [comment]
By the way, what happens when both `-Z` and `-U` is used?

**Comment by intika** [comment]
> By the way, what happens when both `-Z` and `-U` is used?

we got the double protection :) but we loose the "non root" feature because it's enforced by "U"
 

> nice one!! way to go... But I would like this to be the default behavior, i.e the z flag would be turned on by default. Actually there shouldn't be any z flag at all, to turn traceable on we can bring back the old option `-T`.

Yes indeed it makes sens, but as its a new feature i was not willing to put it as default because : 
- i did not take the time to implement backward compatibility for old kernels and some (for prctl.h) 
- i did not implement some essential checks needed for some systems (also for prctl.h) 
- its kind a mitigation because we still can trace the binary after the check function get passed

i also found a solution for the other issue https://github.com/neurobin/shc/issues/7 and will PR soon... but i don't know if i have to add an other flag or just include it in my 'z' flag 

The is many solution... the pipe idea is cool https://github.com/neurobin/shc/issues/51 or just use system call instead of execvp which is what i did... i am looking how to hack system call for the moment to see if its a good solution or not before uploading my code... 

i think i will just add that to the 'z' flag to make it a sort of bundle... let me know if you want it differently (i just have to tell you that i have limited time for the project, i just want it to have acceptable security for my needs... you can still close the PR and re-implement it as you wish of course :) the more important is that the code is shared :+1: ... by the way nice application thanks for taking time making it ;))

**Comment by neurobin** [comment]
> Yes indeed it makes sens, but as its a new feature i was not willing to put it as default because :
> 
>     * i did not take the time to implement backward compatibility for old kernels and some (for prctl.h)
> 
>     * i did not implement some essential checks needed for some systems (also for prctl.h)
> 
>     * its kind a mitigation because we still can trace the binary after the check function get passed
> 

Hmm, seems like adding `-Z` is the best solution for now.

> i think i will just add that to the 'z' flag to make it a sort of bundle

You can add related security to the `Z` flag as you wish. I will see if I need to change it after I merged your PRs.

**Pull request merged**
