### PR TITLE
Remove experimental s feature

### PR DESCRIPTION
**Pull request by intika**
remove s feature not working as expected... i am currently working on a new H version that should be more effective on what it pretend doing

the s feature have 2 issue:
1- it does not really keep the process under a single instance (not possible)
2- the main process get stuck after execution and does not terminate.

### CODE REVIEW

**Comment by neurobin** [comment]
version should be 4.0.2 not 4.0.3

**Comment by neurobin** [comment]
also, you should make the pull request against the master branch. and edit man.md instead of shc.1. shc.1 is auto generated from man.md

**Comment by intika** [comment]
ok i'll do that

**Comment by intika** [comment]
done https://github.com/neurobin/shc/pull/75

**Pull request closed without merging**
